### ISSUE TITLE
YOLO inference example gives ``No module named 'hailo_platform.pyhailort._pyhailort'``

### ISSUE THREAD

**Issue by stwerner97** [hailo-ai/Hailo-Application-Code-Examples#136]
Hi, I've tried running some of the examples with the pyHailoRT. Once I run the ``yolo_inference.py`` script, I get a ``ModuleNotFoundError: No module named 'hailo_platform.pyhailort._pyhailort'`` error.  I've installed ``hailort==4.14.0`` and the other outlined dependency and tried installing ``hailort`` using both the wheel as well as using the pre-build Docker image.

**Comment by omerwer** [comment]
Hi @stwerner97 
In order to use the pyhailort, you need to install the compatible HailoRT .whl file to your virtual env.
The pyhailort .whl can be downloaded from the Hailo website under Developer Zone --> SW downloads.
Notice that the .whl file should match the HailoRT driver version you use and the Python version you use.
For example, if you are using the HailoRT driver v4,13 and Python3.8, then the .whl you need to pip install is `hailort-4.14.0-cp38-cp38-linux_x86_64.whl`

Regards,

**Comment by stwerner97** [comment]
Hi @omerwer, thanks for the response!

I've installed the wheel as you outlined and also tried with the pre-build docker image for HailoRT 4.14.0, but couldn't get it to work. I then also tried HailoRT 4.12.0, where ``import hailo_platform`` doesn't throw the error above.

**Comment by omerwer** [comment]
@stwerner97 Can you please list the environment details in which you are running the example? meaning the OS, system (x86\aarch64), Hailo driver version, Python version etc. in which you are getting the exception?

**Comment by stwerner97** [comment]
@omerwer  here are the specs of the machine.
````
OS: Ubuntu 20.04.4 LTS
System: x86 (64 bits)
Hailo Driver Version: hailort-pcie-driver_4.14.0_all.deb (i.e., 4.14.0)
Python: Python 3.8.10
````
As mentioned, I also tried with the docker image that I downloaded as ``hailort_4.14.0_docker.zip``.

**Comment by omerwer** [comment]
@stwerner97 I'm using the same specs as well and am not getting this error.
Can you try to create a new virtual env, install the 4.14 whl for Python3.8 and re-run? outside of the docker, as a stand alone env.

**Comment by stwerner97** [comment]
Somehow reinstalling the driver did the trick. Thanks for the support! 😊
