### ISSUE TITLE
Unexpected HailoRT Warning Message

### ISSUE THREAD

**Issue by HY1998CN** [hailo-ai/Hailo-Application-Code-Examples#140]
Dear team,

Thank you for your attention, I doubt why there is always this warning message while I run our compiled and converted `.hef` inference engine. Will it affect the performance?

`[HailoRT] [warning] HEF was compiled assuming clock rate of 400 MHz, while the device clock rate is 200 MHz. FPS calculations might not be accurate.`

Best,
Hui

**Comment by omerwer** [comment]
Hi @HY1998CN,
This warning basically means that the default calculations were designed to work with a device that run on 400 MHz, but since your device is set to 200 MHz, it might not be accurate and reflect the performance you'll get when running an application using the Hailo device you own.
Are you using a Hailo8L device?

Regards,

**Comment by HY1998CN** [comment]
Hi @omerwer 

Thank you for your reply. I'm currently using Hailo8 for compilation and inference. Not Hailo8L.

Best regards,
Hui
