### ISSUE TITLE
Examples for 8 bit inference on quantized open source LLMs

### ISSUE THREAD

**Issue by davidwynter** [hailo-ai/Hailo-Application-Code-Examples#162]
I have a potential client who want privacy with air gapped infrastructure. We are looking at the Hailo M.2 key 26 TOPS board used with a 32GB RAM Orange Pi5. Likely using 1-4 fine tuned Zephyr 7B models. 

Thoughts?

**Comment by giladnahor** [comment]
@davidwynter I appreciate your interest. This is indeed a use case for Hailo that we are targeting.
Currently, we support Multi-Head Self-Attention, which has primarily been tested with vision transformers and smaller text transformers. Large Language Models exceeding 2GB encounter compatibility issues due to limitations in our implementation that depends on ONNX and Protobuf. It's possible that smaller models may function within our current framework. Employing 4-bit quantization could further reduce the model size. We are advancing our support for larger LLMs. Stay tuned for an upcoming example showcasing CLIP running on Hailo.
Please feel free to reach out if you have further questions or to share updates on your progress.
Regards,
Gilad

**Comment by davidwynter** [comment]
I can see this being a really strong product. I can comfortably fit 10 Orange Pi5 32GB in a long 1U case with heatsinks top (for RK3588S and RAM) and bottom (for Hailo device) The Pi5 has reasonably fast LPDDR4/4X RAM. The key thing I need to determine is the inference performance before taking the plunge and hosting these as a part of my service.

**Comment by hailocs** [comment]
Hi we will resolve the 2GB limit in the future. Can't commit to a date yet as we are working on higher priority tasks. We will address it as part of our support for LLMs.
