### ISSUE TITLE
Fail to infer from yolov5_yolov7_inference.cpp

### ISSUE THREAD

**Issue by lenam2132002** [hailo-ai/Hailo-Application-Code-Examples#222]
I got the model yolov5m_wo_spp_60p.hef from https://github.com/hailo-ai/hailo_model_zoo/blob/master/docs/PUBLIC_MODELS_HAILO8_Object_Detection.rst and run this code. But I got this issue:
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/142196299/57b7e2a3-882e-4391-ac9e-db7a5ee0e3c9)

Where did I go wrong?

**Comment by omerwer** [comment]
Hi @lenam2132002 ,
The problem was that the default output name was changed in the recent release, so when you used the HEF from the Model Zoo, there code didn't receive what was expected and thus you got the timeout error.
I fixed it and it works fine now.
Please notice that the HEF from the Model Zoo is compiled differently from the HEF we provide in the git:
This is the properties of the Model Zoo HEF:
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/58146682/ee130a0f-001a-4623-970d-68a36804c597)
And this is the properties of the git HEF:
![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/58146682/e6829e54-cbd8-4d9a-bf51-36b9924f269c)
You can see that they differ in the output name (yolov5m_wo_spp_60p/yolov5_nms_postprocess VS yolov5_nms_postprocess , which I now fixed) and the thresholds (0.001\0.6 VS 0.3\0.45). So, if you use the Model Zoo HEF, this would result in many redundant bboxes and would not give you the best accuracy. The code example it built as a stand alone example and works with the supplied files in the git, but not necessarily compiled custom models or Model Zoo models out of the box.

Regards,

**Comment by lenam2132002** [comment]
Thank you very much for your help! I fixed it successfully.
