### ISSUE TITLE
Issue about yolox_streaming_inference

### ISSUE THREAD

**Issue by Hyenni** [hailo-ai/Hailo-Application-Code-Examples#262]
Hello
I'm testing 2I640HL equipment.

Currently, I've even finished converting my custom yolo model to hef format and running it.
For the model execution, I referred to 'object_detection' guide in the hailo application code examples.

However, since the guides uses an image file as the input source, I'd like to connect the webcam to check the model results in streaming, so I tried to run the 'yolox_streaming_inference' guide.

I modified and ran only the model name, path, and labeling part in the file provided by default, but the following error occurs.

I'm attaching the revised file and error message as below,
and I'd appreciate it if you could help me.

![Screenshot from 2024-05-24 12-56-36](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/33708512/4813f8a1-164e-46a4-b2e3-e4033a277f26)

[yolo_streaming_inference.zip](https://github.com/hailo-ai/Hailo-Application-Code-Examples/files/15427695/yolo_streaming_inference.zip)

**Comment by omerwer** [comment]
Hi @Hyenni,
I believe that the error happened because of the HEF format.
Currently, the yolo HEF files are built in with what we call "NMS on Hailo", which basically is running the parts that are not loaded on the HEF on the host, when the part is wrapped with Hailo's SW.

The yolox example is older and doesn't support the newer HEF files. We will add support for a webcam in the near future. 
You can of course change the object_detection.py script to support input from a camera if you like.

Regards,
