### ISSUE TITLE
Inference FPS is 12X lower, latency is almost 7X longer than reported

### ISSUE THREAD

**Issue by talcs** [hailo-ai/Hailo-Application-Code-Examples#272]
Hello,

I have a HEF file with a corresponding "post placement" profiling report, which states that the model's throughput on Hailo8 will be 426 FPS, and latency will be 4.40ms. The HEF file and the profiling report were generated using the Hailo tutorial Jupyter Notebook (Following the "Parsing -> Optimization -> Compilation" flow).

![image](https://github.com/hailo-ai/Hailo-Application-Code-Examples/assets/17887687/8b0c4d12-2e5d-4fe9-be67-81e03f200b47)

However, when I run the HEF file on Hailo8 with sample data images, their typical inference runtime for a batch of 1 image is 28ms (around 35 FPS), such that the actual FPS is 12X lower than reported and latency is almost 7X longer than the reported.

The inference on Hailo8 is done in Python, using the `utils.py` module provided in this repository, under `runtime/python`:

```
import time

import numpy as np
from utils import HailoInference

# Single image batch, preallocated
GRAYSCALE_IMAGE_BATCH = np.zeros((1, 480, 640, 1), dtype = np.uint8)


hailo_inference = HailoInference(HEF_FILE_PATH)

# Measure runtime 15 times, without any pre/post processing
timings = []
for i in range(15):
    t1 = time.time()
    output_tensors = hailo_inference.run(GRAYSCALE_IMAGE_BATCH)
    t2 = time.time()
    timings.append(1000*(t2 - t1))

# Output the median runtime
print(f'{np.median(timings):.1f}ms')
```

The output of the above program is `28.2ms`.

Why is the dramatic difference between the report and the actual performances? What will accelerate the inference?

**Comment by omerwer** [comment]
Hi @talcs,
I'm not sure what model you are running, but the estimated\actual FPS for a model include strictly the FPS of the inference process. When running the Python example, you'll also have the overhead of preprocessing, postprocessing and the built-in latency that generates from using Python compared to C or C++.
Try running the model using the HailoRT CLI tool - in the Linux terminal, run "hailortcli run /path/to/your/vompiled/model.hef" when the Hailo8 device is connected. You should see (give or take) the same result as stated in the profiler report given that the model is compiled in a single context, since I think that the profiler report for multi contexts model is not accurate..

Regards,

**Comment by talcs** [comment]
Hello,

Thank you for the answer.

I executed `hailortcli run HEF_FILE` and did receive runtimes similar to those reported in the profiling report (more than 400 FPS). But how can I get similar numbers when inferencing in Python? My Python example only measures isolated inference time, without any pre or post processing. The difference from the theoretical runtime is not just 5% or 10%, which can be acceptable, it is 1200%, completely unrelated to the theoretical inference time.

It looks like this repository's Python API copies the input and output arrays to and from the Hailo device at every inference, and allocates them each time on the PC. Is it possible, for example, to preallocate everything and allow the user to write their inputs directly to Hailo's memory? Will it save time?

**Comment by talcs** [comment]
I was just able to slightly reduce the runtimes by 2ms, by bypassing the `HailoInference` API and reusing the same `infer_pipeline` object over and over again, without allocating it at every inference like the API does. But it is still dramatically slower than expected.

```
t1 = time.time()
with self.infer_pipeline:
    with self.hailo_inference.network_group.activate(self.hailo_inference.network_group_params):
        self.output_tensors_dict = self.infer_pipeline.infer(input_dict)
t2 = time.time()
print(f'(1000*(t2 - t1)):.1ms')
```
As can be seen, the creation of `input_dict` is not counted, as well as the creation of `self.infer_pipeline`. But its contribution to the runtime is minor, we are still in less than 40 FPS, i.e., more than 10X slower than theoretical 400 FPS.

**Comment by talcs** [comment]
Inference time is reduced to an average of 7.5ms (133 FPS) when all forward calls are done under the same `with` context. We are now just 3X slower than theory.

**Comment by nina-vilela** [comment]
@talcs 

This difference in FPS happens due to the Infer Python API, which only starts writing to the device again once the previous frame is completely sent to the host.

The most optimized way to run inference, and our recommendation, is to use the C++ API (preferably ASync). If you would rather stay with Python, multi-processing with the Send and Recv API would give better results.

**Comment by talcs** [comment]
Thank you. Is there a reference for the Send and Recv API in Python?

**Comment by omerwer** [comment]
Hi @talcs,
Yes, you can see a send\receive example in the DataFlow Compiler user guide or in other python examples in this repo, for example:
https://github.com/hailo-ai/Hailo-Application-Code-Examples/blob/main/runtime/python/hailo_onnxruntime_example/hailo_onnxruntime_inference.py
Just notice that the above example also involves ONNXRuntime, which is not necessarily needed.

Regards,
